import { readFileSync, writeFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

import { templateProjectAppVersion } from '../src/template_project_app_version';

// GENERATED BY gg_version WriteVersionFile - DO NOT EDIT.
//
// Repairs the version literal in
// src/template_project_app_version.ts
// when it drifts from package.json. Drift is not an error here: the literal
// is rewritten and the test passes.

describe('template_project_app_version.ts', () => {
  it('matches the version in package.json', () => {
    const manifest = JSON.parse(readFileSync('package.json', 'utf8')) as {
      version?: string;
    };
    expect(manifest.version).toBeTruthy();

    const declaration = 'export const templateProjectAppVersion = ';
    const expected = `${declaration}'${manifest.version}';`;
    const path = 'src/template_project_app_version.ts';

    if (!readFileSync(path, 'utf8').includes(expected)) {
      writeFileSync(
        path,
        readFileSync(path, 'utf8').replace(
          new RegExp(`${declaration}'[^']*';`),
          expected,
        ),
      );
    }

    expect(readFileSync(path, 'utf8')).toContain(expected);
    expect(templateProjectAppVersion).toBeTruthy();
  });
});
