// GENERATED BY gg_version WriteVersionFile - DO NOT EDIT.
// Kept in sync by test/template_project_app_version.test.ts.

/** The version of the `@tssuite/template-project-app` package. */
export const templateProjectAppVersion = '0.0.3';
